### ISSUE TITLE
feat(util) add the automaticUnsubscribe function as takeUntilDestroy(this) to the library

### ISSUE THREAD

**Issue by Totati** [cloudnc/ngx-observable-lifecycle#16]
Hi, I really like the ide of your `automaticUnsubscribe`, I've already added your lib to 2 of our projects and created a `takeUntilDestroy(this)` function based on yours but I had to do it two times. 
We used to do this:
```typescript  
export class Component implements OnDestroy{
  private readonly onDestroy$ = new Subject<void>();

  constructor(private readonly route: ActivatedRoute){
    this.route.data.pipe(takeUntil(this.onDestroy$).subscribe();
  }

  ngOnDestroy(){
    this.onDestroy$.next();
    this.onDestroy$.complete();
  }
}
```
I believe this is common - we take it from the material repository - and based on this the `takeUntilDestroy` operator name sound better than `automaticUnsubscribe`, and will popup when people strat to write takeUntil 

Thank you

**Comment by zakhenry** [comment]
Hi @Totati, the idea behind this library is that it is the core lifecycle observation feature, and that other libraries should be built with this as a dependency. It's great that you find this library useful, and I encourage you to create a separate ngx-take-until-destroy lib if you would find that useful. I'd like to keep this lib as lean as possible so that libraries that don't need this specific until don't need to import it unnecessarily

**Comment by Totati** [comment]
That's true, but people won't search for that, however when it's in this library they easily spot this feature, and if they don't use it it will be treeshaked away during build.

**Comment by zakhenry** [comment]
closing as this library is intentionally not going to add various utility functions to keep the scope of it fixed.
